version: '2'
services:
    srs-app:
        image: srs
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://srs-mariadb:3306/srs
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    srs-mariadb:
        extends:
            file: mariadb.yml
            service: srs-mariadb
